site_name: SuperComputação - 2022/2
site_author: 

extra:
    materia: SuperComputação
    professor: Luciano Pereira Soares
    semestre: 2022/2
    url_acompanhamentos: http://localhost:8081
    id_curso: 1

theme:
  feature:
    tabs: true
  name: active-handout-theme

docs_dir: material
site_dir: docs

repo_url: https://github.com/insper/supercomp
repo_name: "SuperComp"
site_url: https://insper.github.io/supercomp/


nav:
    - Home: index.md
    - Burocracias: sobre.md

    - Aulas:
        - "A - Reforço C++": aulas/a-reforco-c++/index.md
        - "01 - Introdução": aulas/01-introducao/index.ipynb
        - "02 e 03 - C++": aulas/02-03-implementacao-c++/index.md
        - "04 - Profiling": aulas/04-profiling/index.md
        - "05 - Heurísticas": aulas/05-heuristicas/index.md
        # - "06 - Aleatorização": aulas/06-aleatorizacao/index.md
        # - "07 - Busca Local": aulas/07-busca-local/index.md
        # - "08 - Busca Exaustiva": aulas/08-busca-global/index.md
        # - "09 - Comparação de desempenho": aulas/09-busca-global-II/index.md
        # - "10 - Branch and Bound": aulas/10-branch-and-bound/index.md
        # - "Revisão para P1": aulas/10-branch-and-bound/revisao.md
        # - "11 - Paralelismo": aulas/11-paralelismo/index.md
        # - "12 - Paralelismo - Exercício / Efeitos Colaterais" : aulas/12-efeitos-colaterais/index.md
        # - "13 - Paralelismo - Efeitos Colaterais II":  aulas/13-efeitos-colaterais-II/index.md
        # - "14 - GPU - Introdução":  aulas/14-intro-gpu/index.md
        # - "15 - GPU - Iteradores": aulas/15-gpu-iteradores/index.md
        # - "16 - GPU - Customização": aulas/16-gpu-customizacao/index.md
        # - "17 - GPU - Aleatoriedade": aulas/17-gpu-aleatoriedade/index.md
        # - aulas/13-paralelismo-tarefas-dados/index.md
        # - aulas/14-exercicios/index.md
        # - aulas/15-efeitos-colaterais/index.md
        # - aulas/16-efeitos-colaterais-II/index.md
        

    - Projeto:
        - projetos/index.md
        #- projetos/heuristico.md
        #- projetos/local.md
        #- projetos/exaustiva.md
        #- projetos/openmp.md
        #- projetos/gpu.md
        # - projetos/relatorio-1.md        
        # - projetos/paralelismo-multicore.md
        # - projetos/paralelismo-gpu.md


extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
    - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js

extra_css:
    - css/printing.css
    - css/extra.css

markdown_extensions:
  - active-handout-plugins
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: code
      check_paths: true


plugins:
    - search
    - mknotebooks
